Rename caasp-maintenance-v4 to caasp-maintenance-v4.2
SUSE/skuba pull request #1357
Opened 2020-09-14 15:48 UTC by jordimassaguerpla

Because CaaSP 4.5 is master, so to avoid confusions.

fixes https://github.com/SUSE/avant-garde/issues/1866

2020-09-14 15:53 UTC, jordimassaguerpla commented
maintenance-caasp-v4.2 needs to be rebased

2020-09-14 15:54 UTC, jordimassaguerpla commented
After merging this, maintenance-caasp-v4 should be renamed to old-maintenance-caasp-v4

2020-09-16 08:59 UTC, Itxaka approved these changes
lgtm

2020-09-16 10:49 UTC, pablochacin requested changes

2020-09-16 10:49 UTC, pablochacin commented on ci/jenkins/jobs.yaml
>            - v4:
I would change this to 4.2 for consistency

2020-09-17 11:05 UTC, pablochacin commented
I noticed that this PR is against the maintenance-v4 branch and it is unnecessary because the job definition is only read from master. I'm more in the line of either a) removing the job definition from this branch to avoid confusion or b) backport the definition from master to updated it.

2020-09-17 11:48 UTC, jordimassaguerpla commented
@pablochacin what is the simplest thing to do ?

2020-09-18 09:37 UTC, jordimassaguerpla commented
We do not need this one. The jobs we run are from master. We should instead remove the jobs because this is confusing.

2020-09-18 09:37 UTC, closed without merging