[4.2] addons: List cilium-init image only for Cilium < 1.6
SUSE/skuba pull request #1397
Opened 2020-10-14 11:30 UTC by mrostecki

We don't ship a separate cilium-init image anymore. The cilium-init
script is included in the main cilium container image.

Fixes: SUSE/avant-garde#1923

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

2020-10-14 19:04 UTC, soumynathan reviewed
Looks good to me.

2020-10-15 08:45 UTC, mmnelemane reviewed
Isnt it possible to plainly skip the test altogether if the version is above 1.6 instead of running a dummy string test ?

2020-10-15 08:47 UTC, mmnelemane requested changes
Is it possible to skip the call to GetCiliumInitImage() here instead of passing an empty string ?

2020-10-15 09:22 UTC, mrostecki commented
> Isnt it possible to plainly skip the test altogether if the version is above 1.6 instead of running a dummy string test ?

What do you mean?

> Is it possible to skip the call to GetCiliumInitImage() here instead of passing an empty string ?

Not really. Look here:

https://github.com/SUSE/skuba/blob/a019c9193ef068044f8b956e7ad96e618780ccf4/internal/pkg/skuba/addons/cilium.go#L34

```
[]getImageCallback{GetCiliumInitImage, GetCiliumOperatorImage, GetCiliumImage}
```

The `registerAddon` function expects the full slice with `getImageCallback` functions. Since it's called in the `init` function, you cannot pass any arguments there, so you can't determine the version when callbacks are registered.

Honesly, I don't think there is any better way of handling different versions without a huge rewrite of the whole addons mechanism, but I'm open for suggestions.

Also, keep in mind that this is a backport and the same change is already merged in master (#1396). So if there is any other way of handling the <1.6 case which would be better for you, we would need to push it to master first.

2020-10-15 09:41 UTC, mmnelemane commented
> > Isnt it possible to plainly skip the test altogether if the version is above 1.6 instead of running a dummy string test ?
> 
> What do you mean?
> 
> > Is it possible to skip the call to GetCiliumInitImage() here instead of passing an empty string ?
> 
> Not really. Look here:
> 
> https://github.com/SUSE/skuba/blob/a019c9193ef068044f8b956e7ad96e618780ccf4/internal/pkg/skuba/addons/cilium.go#L33-L35
> 
> ```
> []getImageCallback{GetCiliumInitImage, GetCiliumOperatorImage, GetCiliumImage}
> ```
> 
> The `registerAddon` function expects the full slice with `getImageCallback` functions. Since it's called in the `init` function, you cannot pass any arguments there, so you can't determine the version when callbacks are registered.
> 
> Honesly, I don't think there is any better way of handling different versions without a huge rewrite of the whole addons mechanism, but I'm open for suggestions.
> 
> Also, keep in mind that this is a backport and the same change is already merged in master (#1396). So if there is any other way of handling the <1.6 case which would be better for you, we would need to push it to master first.

Sorry, I was only referring to the test code here: https://github.com/SUSE/skuba/pull/1397/files#diff-5f300cc81d08e60d6fa85478fa933ba35c084d1d3c2a7b31f5fdc12ac075dda1R50. where you are passing an empty string ? Again, its not very crucial.. just a suggestion. Otherwise Looks Good to me.

2020-10-15 09:42 UTC, mmnelemane submitted a review, later dismissed

2020-12-11 12:23 UTC, manuelbuil approved these changes

2020-12-11 12:45 UTC, merged